name: root

channels:
  - conda-forge

dependencies:
  - python=3.6
  - sympy
  - nltk
  - htop
  - tmux
  - blinker=1.4=py36_0
  - nano>=2.4.1
  - numpy>=1.13.1
  - scipy
  - jupyter
  - ipyparallel
  - pandas>=0.20.1
  - matplotlib>=2.0.2
  - scikit-learn>=0.19.0
  - seaborn
  - patsy
  - seaborn
  - tweepy
  - traitlets
  - statsmodels
  - tensorflow
  - scikit-image
  - requests
  - curl
  - xz
  - r-base
  - r-recommended>=3.4.1
  - r-irkernel
  - numba
  - beautifulsoup4
  - bokeh
  - toolz
  - julia
  - pip:
    - keras
    - mwapi
    - wikipedia
    - Theano
    - pywikibot
    - docopt
    - getorg
    - tweepy
