permalink: /posts/:year-:month-:day-:title.html

future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github:
  owner_url: https://github.com/thehackerwithin/berkeley
url: http://thehackerwithin.org/berkeley 
name: Hacker Within
chapter: Berkeley
description: An initial blog and site for THW at UCB
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: 

